version: '2'
services:
  cachet:
    build:
      context: .
      args:
        - cachet_ver=master
    environment:
      APP_KEY: overwriteme
      APP_LOG: errorlog
      DB_DATABASE: cachetdb
      DB_DRIVER: mysql
      DB_HOST: cachet-dev.connectedfleet.io
      DB_PASSWORD: overwriteme
      DB_PORT: '3306'
      DB_PREFIX: chq_
      DB_USERNAME: overwriteme
      DEBUG: 'false'
    entrypoint:
    - /bin/bash
    ports:
    - 2020:8000/tcp
    secrets:
    - mode: 444
      uid: '0'
      gid: '0'
      source: cachet-app-key
      target: APP_KEY
    - mode: 444
      uid: '0'
      gid: '0'
      source: cachet-db-password
      target: DB_PASSWORD
    - mode: 444
      uid: '0'
      gid: '0'
      source: cachet-db-username
      target: DB_USERNAME  
    command:
    - -c
    - |-
      . /run/secrets/APP_KEY \
      && . /run/secrets/DB_USERNAME \
      && . /run/secrets/DB_PASSWORD \
      && /sbin/entrypoint.sh
    labels:
      traefik.port: '8000'
      traefik.enable: 'true'
      io.rancher.container.hostname_override: container_name
      traefik.domain: dev.connectedfleet.io
      traefik.alias: cachet
secrets:
  cachet-app-key:
    external: 'true'
  cachet-db-password:
    external: 'true'
  cachet-db-username:
    external: 'true'
